# we configuring 2 different virtual machines in order to get both ubuntu and centos OS(s)
#

Vagrant.configure(2) do |config|
  config.vm.define "jmaster" do |jmaster|
      jmaster.vm.box = "bento/ubuntu-16.04"
      jmaster.vm.hostname = "jmaster"
      jmaster.vm.network "private_network", ip: "192.168.33.18"

      jmaster.vm.provision "chef_solo" do |chef|
        chef.cookbooks_path = "chef/cookbooks"
        chef.roles_path = "chef/roles"
        chef.add_role("jenkins")
        chef.environments_path = "chef/environments"
        chef.environment = "development"
      end
  end




end
