# we configuring 2 different virtual machines in order to get both ubuntu and centos OS(s)
#

Vagrant.configure(2) do |config|
  config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "bento/ubuntu-16.04"
      ubuntu.vm.hostname = "ubuntu"
      ubuntu.vm.network "private_network", ip: "192.168.33.18"
  end

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "chef/cookbooks"
    chef.roles_path = "chef/roles"
    chef.add_role("jenkins")
    chef.environments_path = "chef/environments"
    chef.environment = "development"
  end


end
