node_name "someapp"
file_cache_path    "/var/chef/cache"
file_backup_path   "/var/chef/backup"
cookbook_path ["/tmp/chef/cookbooks"]
role_path "/tmp/chef/roles"
log_level :info
verbose_logging false
encrypted_data_bag_secret nil
environment_path "/tmp/vagrant-chef/eb5c8a883ffcefc345d7634e367d1e98/environments"
environment "development"
http_proxy nil
http_proxy_user nil
http_proxy_pass nil
https_proxy nil
https_proxy_user nil
https_proxy_pass nil
no_proxy nil